# Generated by Django 2.0 on 2021-04-06 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_auto_20210405_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
